version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/"
    cooldown:
      default-days: 7
      exclude:
        - "databricks*"
    schedule:
      interval: "daily"

  # Disabled for now, pending
  #- package-ecosystem: "github-actions"
  #  directory: "/"
  #  schedule:
  #    interval: "daily"
