name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
          python-version: '3.10'
      
      - name: Build wheels
        run: |
          pip install hatch==1.7.0
          hatch build

      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/databricks_*.whl
            dist/databricks_*.tar.gz

      - uses: pypa/gh-action-pypi-publish@release/v1
        name: Publish package distributions to PyPI